#!/bin/bash
set -e
cd "$(dirname "$0")/../.."

cd test

apt update
DEBIAN_FRONTEND=noninteractive apt-get install -qq qpdf

pip install --upgrade ../

# runs a test file with PASS/FAIL message
run_test() {
  (python "$1" && echo "PASS $1 (Python $version)") || (echo "FAIL $1 (Python $version)"; exit 1)
}

if [ "$1" == "" ]; then
  for test in *.py; do
    run_test "$test"
  done
else
  run_test "$1.py"
fi
