# coding: utf-8

"""
    DocRaptor

    A native client library for the DocRaptor HTML to PDF/XLS service.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import docraptor
from docraptor.api.doc_api import DocApi  # noqa: E501
from docraptor.rest import ApiException


class TestDocApi(unittest.TestCase):
    """DocApi unit test stubs"""

    def setUp(self):
        self.api = docraptor.api.doc_api.DocApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_async_doc(self):
        """Test case for create_async_doc

        """
        pass

    def test_create_doc(self):
        """Test case for create_doc

        """
        pass

    def test_create_hosted_async_doc(self):
        """Test case for create_hosted_async_doc

        """
        pass

    def test_create_hosted_doc(self):
        """Test case for create_hosted_doc

        """
        pass

    def test_expire(self):
        """Test case for expire

        """
        pass

    def test_get_async_doc(self):
        """Test case for get_async_doc

        """
        pass

    def test_get_async_doc_status(self):
        """Test case for get_async_doc_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
