# coding: utf-8

"""
    DocRaptor

    A native client library for the DocRaptor HTML to PDF/XLS service.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import docraptor
from docraptor.models.prince_options import PrinceOptions  # noqa: E501
from docraptor.rest import ApiException

class TestPrinceOptions(unittest.TestCase):
    """PrinceOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PrinceOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = docraptor.models.prince_options.PrinceOptions()  # noqa: E501
        if include_optional :
            return PrinceOptions(
                baseurl = '', 
                no_xinclude = True, 
                no_network = True, 
                no_parallel_downloads = True, 
                http_user = '', 
                http_password = '', 
                http_proxy = '', 
                http_timeout = 56, 
                insecure = True, 
                media = 'print', 
                no_author_style = True, 
                no_default_style = True, 
                no_embed_fonts = True, 
                no_subset_fonts = True, 
                no_compress = True, 
                encrypt = True, 
                key_bits = 56, 
                user_password = '', 
                owner_password = '', 
                disallow_print = True, 
                disallow_copy = True, 
                disallow_annotate = True, 
                disallow_modify = True, 
                debug = True, 
                input = 'html', 
                version = '', 
                javascript = True, 
                css_dpi = 56, 
                profile = '', 
                pdf_title = ''
            )
        else :
            return PrinceOptions(
        )

    def testPrinceOptions(self):
        """Test PrinceOptions"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
