# coding: utf-8

"""
    DocRaptor

    A native client library for the DocRaptor HTML to PDF/XLS service.  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import docraptor
from docraptor.models.doc_status import DocStatus  # noqa: E501
from docraptor.rest import ApiException

class TestDocStatus(unittest.TestCase):
    """DocStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DocStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = docraptor.models.doc_status.DocStatus()  # noqa: E501
        if include_optional :
            return DocStatus(
                status = '', 
                download_url = '', 
                download_id = '', 
                message = '', 
                number_of_pages = 56, 
                validation_errors = ''
            )
        else :
            return DocStatus(
        )

    def testDocStatus(self):
        """Test DocStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
