#!/bin/bash
set -e
cd "$(dirname "$0")/.."

echo "Removing trailing whitespace..."
find docraptor -name "*.py" -type f -exec sed -E -i '' 's/[[:space:]]+$//g' {} +

echo "Removing auto generated tests..."
rm test/test_*.py

echo "Removing auto generated docs..."
rm -r docs

if compgen -G "patches/*.patch" > /dev/null; then
  echo "Apply patches to generated code"
  git apply --verbose patches/*.patch
fi
