#!/bin/bash
set -e
cd "`dirname \"$0\"`/.."

cd test

rm -rf venv
which virutualenv || pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install ../

# runs a test file with PASS/FAIL message
run_test() {
  python $1 && echo "PASS $1" || (echo "FAIL $1"; exit 1)
}

if [ "$1" == "" ]; then
  for test in $(ls *.py); do
    run_test $test
  done
else
  run_test $1.py
fi
